baseURL = "https://ajossorioarana.github.io/"
title = "Arturo J. Ossorio Arana"
paginate = 5
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
googleAnalytics = "UA-123-45"
pygmentsUseClasses = true
copyright = "© CC-BY-4.0"

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Arturo J. Ossorio Arana"
description = "Data & Modeling in Ecohydrology's Dynamic & Rich Tapestry"
keywords = [ "Blog", "Portfolio", "PaperMod" ]
author = "Arturo J. Ossorio Arana"
mainSections = ["blog", "projects"]
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "light"
disableThemeToggle = true
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = false
ShowBreadCrumbs = false
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false
math = true


  [params.assets]
  favicon = "icons/nature.png"
  favicon16x16 = "icons/nature.png"
  favicon32x32 = "icons/nature.png"
  apple_touch_icon = "icons/nature.png"
  safari_pinned_tab = "icons/nature.png"
  disableHLJS = false
  

  [params.label]
  text = "Home"
  icon = "icons/nature.png"
  iconHeight = 35

# JUST USE IF PROFILE MODE

#   [params.profileMode]
#   enabled = false
#   title = "ExampleSite"
#   subtitle = "This is subtitle"
#   imageUrl = "<img location>"
#   imageWidth = 120
#   imageHeight = 120
#   imageTitle = "my image"

#     [[params.profileMode.buttons]]
#     name = "Posts"
#     url = "posts"

#     [[params.profileMode.buttons]]
#     name = "Tags"
#     url = "tags"

  [params.homeInfoParams]
  Title = "Arturo J. Ossorio Arana"
  Content = "Data & Modeling in Ecohydrology's Dynamic & Rich Tapestry"
  
  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/ajossorioarana"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/ajossorioarana"

  [[params.socialIcons]]
  name = "stackoverflow"
  url = "https://stackoverflow.com/users/20055088/arthuroa"


[params.analytics.google]
SiteVerificationTag = "XYZabc"

[params.analytics.bing]
SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.editPost]
  URL = "https://github.com/ajossorioarana/ajossorioarana.github.io/content"
  Text = "Suggest Changes"
  appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
name = "about"
url = "/about"
weight = 10

[[menu.main]]
name = "archive"
url = "/archives"
weight = 50

[[menu.main]]
name = "blog"
url = "/blog"
weight = 20

[[menu.main]]
name = "projects"
url = "/projects"
weight = 30

[[menu.main]]
name = "tags"
url = "/tags"
weight = 40

[[menu.main]]
name = "resume"
url = "/resume.pdf"
weight = 60
